### ISSUE TITLE
Android Redirect

### ISSUE THREAD

**Issue by td-edge** [oktadeveloper/okta-ionic-social-login-example#5]
In your instructions, you mention needing to add the okta redirect to the info.plist for iOS. Is there a similar step needed for android's build.gradle files? I get to the point where I log in on android, but it won't redirect back to the application.

**Comment by mraible** [comment]
Change the custom scheme in `android/app/src/main/res/values/strings.xml` to use your reverse domain name:

```xml
<string name="custom_url_scheme">com.okta.dev-737523</string>
```

**Comment by td-edge** [comment]
That seemed to work perfectly. Thank you!
